services:
  product-db:
    image: postgres:16
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    ports:
      - "5433:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  inventory-db:
    image: postgres:16
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_password
    ports:
      - "5435:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
    ports:
      - "5436:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

volumes:
  product_db_data:
  order_db_data:
  inventory_db_data:
  payment_db_data:
